manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: grasegger
      url-base: https://github.com/grasegger
  projects:
    - name: zmk
      remote: zmk
      revision: main
      import: app/west.yml
  self:
    path: config
